name: Build EXE (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (onedir)
        shell: powershell
        run: |
          pyinstaller `
            --noconfirm `
            --windowed `
            --onedir `
            --name "CopyEnvelope" `
            --icon assets/app.ico `
            --add-data "assets/app.png;assets" `
            app.py
          Write-Host "Built files:"
          Get-ChildItem -Recurse .\dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CopyEnvelope-dist
          path: dist

